# Generated by BoostInstall.cmake for boost_msm-1.82.0

include(CMakeFindDependencyMacro)

find_dependency(boost_any 1.82.0 EXACT)
find_dependency(boost_assert 1.82.0 EXACT)
find_dependency(boost_bind 1.82.0 EXACT)
find_dependency(boost_circular_buffer 1.82.0 EXACT)
find_dependency(boost_config 1.82.0 EXACT)
find_dependency(boost_core 1.82.0 EXACT)
find_dependency(boost_function 1.82.0 EXACT)
find_dependency(boost_fusion 1.82.0 EXACT)
find_dependency(boost_mpl 1.82.0 EXACT)
find_dependency(boost_parameter 1.82.0 EXACT)
find_dependency(boost_phoenix 1.82.0 EXACT)
find_dependency(boost_preprocessor 1.82.0 EXACT)
find_dependency(boost_proto 1.82.0 EXACT)
find_dependency(boost_serialization 1.82.0 EXACT)
find_dependency(boost_tuple 1.82.0 EXACT)
find_dependency(boost_type_traits 1.82.0 EXACT)
find_dependency(boost_typeof 1.82.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_msm-targets.cmake")
