# Generated by BoostInstall.cmake for boost_contract-1.82.0

include(CMakeFindDependencyMacro)

find_dependency(boost_any 1.82.0 EXACT)
find_dependency(boost_assert 1.82.0 EXACT)
find_dependency(boost_config 1.82.0 EXACT)
find_dependency(boost_core 1.82.0 EXACT)
find_dependency(boost_exception 1.82.0 EXACT)
find_dependency(boost_function 1.82.0 EXACT)
find_dependency(boost_function_types 1.82.0 EXACT)
find_dependency(boost_mpl 1.82.0 EXACT)
find_dependency(boost_optional 1.82.0 EXACT)
find_dependency(boost_preprocessor 1.82.0 EXACT)
find_dependency(boost_smart_ptr 1.82.0 EXACT)
find_dependency(boost_static_assert 1.82.0 EXACT)
find_dependency(boost_thread 1.82.0 EXACT)
find_dependency(boost_type_traits 1.82.0 EXACT)
find_dependency(boost_typeof 1.82.0 EXACT)
find_dependency(boost_utility 1.82.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_contract-targets.cmake")
