# Generated by BoostInstall.cmake for boost_gil-1.82.0

include(CMakeFindDependencyMacro)

find_dependency(boost_assert 1.82.0 EXACT)
find_dependency(boost_concept_check 1.82.0 EXACT)
find_dependency(boost_config 1.82.0 EXACT)
find_dependency(boost_container_hash 1.82.0 EXACT)
find_dependency(boost_core 1.82.0 EXACT)
find_dependency(boost_filesystem 1.82.0 EXACT)
find_dependency(boost_integer 1.82.0 EXACT)
find_dependency(boost_iterator 1.82.0 EXACT)
find_dependency(boost_mp11 1.82.0 EXACT)
find_dependency(boost_preprocessor 1.82.0 EXACT)
find_dependency(boost_type_traits 1.82.0 EXACT)
find_dependency(boost_variant2 1.82.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_gil-targets.cmake")
