# Generated by BoostInstall.cmake for boost_json-1.82.0

include(CMakeFindDependencyMacro)

find_dependency(boost_align 1.82.0 EXACT)
find_dependency(boost_assert 1.82.0 EXACT)
find_dependency(boost_config 1.82.0 EXACT)
find_dependency(boost_container 1.82.0 EXACT)
find_dependency(boost_core 1.82.0 EXACT)
find_dependency(boost_describe 1.82.0 EXACT)
find_dependency(boost_mp11 1.82.0 EXACT)
find_dependency(boost_system 1.82.0 EXACT)
find_dependency(boost_throw_exception 1.82.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_json-targets.cmake")
