# Generated by BoostInstall.cmake for boost_locale-1.82.0

include(CMakeFindDependencyMacro)

find_dependency(boost_assert 1.82.0 EXACT)
find_dependency(boost_config 1.82.0 EXACT)
find_dependency(boost_iterator 1.82.0 EXACT)
find_dependency(boost_core 1.82.0 EXACT)
find_dependency(boost_predef 1.82.0 EXACT)
find_dependency(boost_thread 1.82.0 EXACT)
find_dependency(ICU COMPONENTS  data i18n uc)

include("${CMAKE_CURRENT_LIST_DIR}/boost_locale-targets.cmake")
