# Generated by BoostInstall.cmake for boost_nowide-1.82.0

include(CMakeFindDependencyMacro)

find_dependency(boost_config 1.82.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_nowide-targets.cmake")
