# Generated by BoostInstall.cmake for boost_stl_interfaces-1.82.0

include(CMakeFindDependencyMacro)

find_dependency(boost_assert 1.82.0 EXACT)
find_dependency(boost_config 1.82.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_stl_interfaces-targets.cmake")
