# Generated by BoostInstall.cmake for boost_yap-1.82.0

include(CMakeFindDependencyMacro)

find_dependency(boost_hana 1.82.0 EXACT)
find_dependency(boost_preprocessor 1.82.0 EXACT)
find_dependency(boost_type_index 1.82.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_yap-targets.cmake")
